title: GPGPU with GLES documentation
author: "Jakub Duchniewicz"
description: > # this means to ignore newlines until "show_excerpts:"
  Documentation for Google Summer of Code 2021 BeagleBone project GPGPU with GLES.

color_scheme: "dark"
search_enabled: false

github_username: JDuchniewicz

remote_theme: pmarsceill/just-the-docs

header_pages:
  - _pages/frontpage.md

include:
  - _pages
    
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
